### ISSUE TITLE
ValueSets Fertigstellen

### ISSUE THREAD

**Issue by 1anja1** [HL7Austria/ELGA-MOPED-R5#108]
Alle Valuesets müssen fertiggestellt werden. Es muss überprüft werden, ob alle referenzierten ValueSets existieren und wenn nicht diese erstellen.  TBD Ticket genau ausformulieren

Danach müssen alle relevanten ValueSets in einen ZIP Folder gegeben werden -> für pineIT zum Upload für die Validierung

**Comment by 1anja1** [comment]
Valuesets die noch fehlen:
LKFAbrechnungsGruppe
LKFAbrechnungsKnoten
Sonderleistungsnummer
VAEStatus
VerpflegskostenBeitragsbefreiung?

**Comment by alackerbauer** [comment]
LKF Abrechnungsgruppe Werteausprägungen: 

* **DIAG0PKT** bei Patient:innen, deren codierte Hauptdiagnose für einen stationären Aufenthalt
alleine nicht plausibel ist
* **FEHLER** bei fehlerhaften Datensätzen
* **GERIAT** bei Patient:innen mit ausschließlichem Aufenthalt auf einer Einheit für Akutgeriatrie/Remobilisation
* **HKLE** bei Patient:innen mit ausschließlichem Aufenthalt auf einer Einheit für hochkontagiöse lebensbedrohliche Erkrankungen
* **KJP** bei Patient:innen mit ausschließlichem Aufenthalt auf einer Einheit für Kinder- und
Jugendpsychiatrie
* **LANGZEIT** bei der Aufnahmeart "L"
* **NEURO** bei Patient:innen mit ausschließlichem Aufenthalt auf einer Einheit für Akut-Nachbehandlung von neurologischen Patienten
* **PALLIAT** bei Patient:innen mit ausschließlichem Aufenthalt auf einer palliativmedizinischen
Einheit
* **PFLEGE** bei der Aufnahmeart "P"
* **REMOB** bei Patient:innen mit ausschließlichem Aufenthalt auf einer Einheit für
Remobilisation/Nachsorge
* **VERBLEIB** bei am Jahresende verbleibenden Patient:innen

**Comment by alackerbauer** [comment]
# Werte VKBEFR – Verpflegskosten-Beitragsbefreiung
1 Stelle alphanumerisch
* `J` – Befreiung
* `N` – keine Befreiung
* `S` – Befreiung aufgrund der Sonderklasse

Genauere Beschreibungen:
* J: Es liegt eine Befreiung vom Verpflegskostenbeitrag aufgrund einer bundes- oder landesgesetzlichen Gesetzesbestimmung bzw. eines Arbeitsunfalls oder einer Rezeptgebührenbefreiung vor.
* N: Es liegt keine Befreiung vom Verpflegskostenbeitrag vor.
* S: Es liegt eine Befreiung vom Verpflegskostenbeitrag aufgrund eines gemeldeten Aufenthaltes von
Patienten in der Sonderklasse vor (BVAEB-EB, SVS-GW, BVAEB-OEB)

**Comment by alackerbauer** [comment]
# D.33. VAEST – Status der Versichertenanspruchserklärung
VAE Status: Siehe Seite 78 hier: https://www.sozialversicherung.at/cdscontent/load?contentid=10008.787666&version=1714375049

Hiervon sind die Codes und Bezeichnungen relevant.

**Comment by alackerbauer** [comment]
# D.40. SOND – Sonderleistungsnummer
2 Stelle alphanumerisch
* `00` – orthopädisches Hilfsmittel (Körperersatzstücke), die nicht therapeutische Behelfe darstellen
* `01` – Ersatz der Kosten für den fallweisen Beistand durch eine nicht in der Anstalt angestellte
Hebamme

**Comment by 1anja1** [comment]
### Altersgruppe
1. Spalte ist der Code
2. Spalte ist die Description
<img width="990" alt="370685003-6535f24a-93b2-470d-a250-c74c8e586cdd" src="https://github.com/user-attachments/assets/9aa7e8f0-271d-4967-9164-da532c283b72">

**Comment by alackerbauer** [comment]
# LKF Abrechnungsknoten:
* `A`
* `B`
* `C`
* `C`
* `D`
* `E`
* `F`
* `G`
* `H`

**Comment by alackerbauer** [comment]
Für die LKF-Abrechnungsgruppe sollten jedenfalls die Werte enthalten sein, die in unseren Beispielen vorkommen. @1anja1 könntest du diese hier kommentieren?
