### ISSUE TITLE
MBDS Felder Leistungszuständiger Kostenträger & Abrechnender Kostenträger

### ISSUE THREAD

**Issue by 1anja1** [HL7Austria/ELGA-MOPED-R5#121]
diese sind im Account hinterlegt, müssen dann aber im Claim auch ausgeliefert werden und somit auch Teil des Claims sein -> wie bilden wir das in der Mapping Tabelle ab? Beide Paths hineinschreiben?

**Comment by alackerbauer** [comment]
ja beide PATHs werden gut (wo kann diese Info ausgelesen werden vs. wohin kommt sie bei Auslieferung).

**Comment by 1anja1** [comment]
wird in #98 erledigt
