### ISSUE TITLE
Änderungen für die physische Anwesenheit in den Operations nachziehen

### ISSUE THREAD

**Issue by 1anja1** [HL7Austria/ELGA-MOPED-R5#126]
physische Anwesenheit kommt als Parameter in $aufnehmen, $verlegen und $beurlauben vor und muss somit in den Beschreibungen der Operations an das neue Mapping: TransferEncounter.subjectStatus angepasst werden
#125 
#103

**Comment by alackerbauer** [comment]
siehe outcome der frage aus dem AG Moped hier: https://hl7at.atlassian.net/wiki/spaces/BAL/pages/201359362/2024-10-03+4.+Termin+AG+FHIR+Moped
