### ISSUE TITLE
Check ob Überweisende Organisation auch VPNR verwendet

### ISSUE THREAD

**Issue by alackerbauer** [HL7Austria/ELGA-MOPED-R5#127]
Im Beispiel in der Postman Collection sowie den Beispielen im IG zum Thema Aufnahme-Bundle: wird hier als überweisende Organisation auch wie im es sein sollte die VPNR als conditional Reference angegeben, oder wird hier ein anderer Identifizierer angegeben oder wird die Organization gänzlich unterschiedlich dargestellt?

Zu prüfen sind folgende Stellen:
* [Postman Collection Main](https://github.com/HL7Austria/ELGA-MOPED-R5/blob/main/postman/MOPED%20TEST%201.postman_collection.json)
* [Examples, konkret bei der Referenz des Aufnahme-Encounters](https://github.com/HL7Austria/ELGA-MOPED-R5/tree/main/input/fsh/examples)

**Comment by simonesan** [comment]
Ich bin mir nicht ganz sicher, was ich in dem Issue genau machen soll. @alackerbauer 
Ich habe mir die Überweißenden Organisation im Postman Request Body angesehen. Hier ist keine VPNR in Verwendung:
![grafik](https://github.com/user-attachments/assets/984ce538-f00d-4eb5-8843-05214c033d5f)
Bei den Example Files wird beim Test1 bei der Überweißenden Organisation auch keine VPNR angegeben:
 ![grafik](https://github.com/user-attachments/assets/bf3cbcfd-18d9-4204-a8c4-6156d18d862c)
Beim Test 2 jedoch schon:
![grafik](https://github.com/user-attachments/assets/35cee4f9-be9e-4a99-9ff5-f460afd8a8db)

Soll ich da jetzt irgendwas anpassen?
