### ISSUE TITLE
Medizinische Leistung - Anzahl

### ISSUE THREAD

**Issue by 1anja1** [HL7Austria/ELGA-MOPED-R5#129]
Wie hängen Anzahl und datum der medizinischen Leistung zusammen? - Datum nur das erste vorkommen der Leistung? -> evtl. Sebastian fragen

<img width="227" alt="Screenshot 2024-10-01 at 15 29 09" src="https://github.com/user-attachments/assets/2455c34b-63b4-4a1e-8cde-4fe3ce660010">

**Comment by 1anja1** [comment]
wird behandelt in #195

**Comment by alackerbauer** [comment]
eingriff zu einem zeitpunkt aber bezahlt wird pro gefäß - 3 einheiten

bei zwei sitzungen sind es im gegensatz dazu 2 x04 mit 2 verschiedenen dati

und dann gibt es noch leistungseinheit je Seit, weil das LKF modell nur links oder rechts erkennt, wenn beidseits ergibt das 2x x04 einmal links und einmal rechts, obwohl es zum gleichen zeitpunkt stattgefunden hat
