### ISSUE TITLE
Filter `_elements` für Bundle

### ISSUE THREAD

**Issue by alackerbauer** [HL7Austria/ELGA-MOPED-R5#147]
Die Suche `GET {{server-base}}/CoverageEligibilityRequest?status=active&_include=*` liefert bereits mehrere Ressourcen-Typen in einem Bundle zurück (Beispiel CoverageEligibilityRequest, Patient, Coverage, Organization).

Ich möchte gerne bestimmte Elemente filtern - es ist ausreichend wenn es zu Beginn ganz bestimmte und einzelne sind, die ich als "whitelist" sehen darf. Ein Beispiel dafür wäre das Geburtsdatum des Patienten das das einzige Element ist das ich sehen darf.

Dafür würde sich der Filter `_elements` grundsätzlich eignen. 

Wie sieht der Output aus, wenn _elements auf einem Bundle mit verschiedenen Ressourcen-Typen angewandt wird? 

`GET {{server-base}}/CoverageEligibilityRequest?status=active&_include=*&_elements=gender`

Es ist einfach, wenn es ein definierter Suchparameter ist, der wie in diesem Fall nur auf Patient zutrifft. Wie sieht das aus bei Suchparametern, die in mehreren Ressourcen vorkommen und gleich heißen, beispielsweise `identifier`? Gibt es Möglichkeiten, zu unterscheiden, wie beispielsweise `Coverage.identifier` vs. `Patient.identifier`?

**Comment by alackerbauer** [comment]
https://hl7.org/fhir/search.html

**Comment by alexandradenk** [comment]
![Image](https://github.com/user-attachments/assets/16de33f9-1cef-436b-ab4f-db732557970a)
Zum ausgewählten "Pfad" werden immer die Metainformationen und die ID der Resource angezeigt.
