### ISSUE TITLE
Nullflavor in FHIR - wie abgebildet?

### ISSUE THREAD

**Issue by alackerbauer** [HL7Austria/ELGA-MOPED-R5#158]

**Comment by 1anja1** [comment]
Mit der extension data-absent-reason und dem code masked
![image (1)](https://github.com/user-attachments/assets/38176e7e-d563-49eb-8cf3-0d2a3e12ac07)

![Screenshot 2024-10-11 at 20 48 41](https://github.com/user-attachments/assets/c595d79b-9d3b-410a-bff4-65a8d6033bb4)

Beispiel
[https://build.fhir.org/ig/HL7/fhir-ips/StructureDefinition-MedicationStatement-uv-ips-definitions.html#MedicationStatement.e[…]on:data-absent-reason](https://build.fhir.org/ig/HL7/fhir-ips/StructureDefinition-MedicationStatement-uv-ips-definitions.html#MedicationStatement.effective[x].extension:data-absent-reason)

**Comment by 1anja1** [comment]
Nullflavor extension für alle Felder in LGF bzw. Bund Profile einfügen, die nicht übermittelt werden dürfen aber aufgrund des Profils verpflichtend sind. -> bei allen anderen Feldern Cardinality auf 0 setzen

**Comment by alackerbauer** [comment]
hier ein Beispiel zu Patient.name: https://github.com/HL7/fhir-mdi-ig/blob/master/input/fsh/instances/us-core-patient-unknown-name.fsh#L13
