### ISSUE TITLE
Altersgruppe für Zugang und Entlassung

### ISSUE THREAD

**Issue by 1anja1** [HL7Austria/ELGA-MOPED-R5#163]
momentan nur 1 Feld Altersgruppe - ist aber für Zugang und Entlassung notwendig -> extension anpassen

**Comment by 1anja1** [comment]
@alackerbauer wie setzen wir das am schönsten um? complex extension mit 2 code feldern einmal für Zugang und einmal für Entlassung? oder mit einem slice auf die extension?

**Comment by alackerbauer** [comment]
werde das in die AG Moped mitnehmen.

**Comment by alackerbauer** [comment]
Lt. AG Moped: Wir sollen ein Complex Extension vorbereiten. Diese beinhält idealerweise Altergruppe bei Zugang, Altersgruppe bei Abgang sowie die Extension, ob es sich um ein Neugeborenes handelt. Bzgl. "Neugeborenes" kann man das mit einer invariant befüllen, dass dieses nur "true" sein darf, falls die Altergruppe bei Zugang mit dem Code "0" befüllt wurde.

Brauchen wir auch "Neugeborenes" bei Abgang?

**Comment by 1anja1** [comment]
X01: Altersgruppe bei Entlassung 
X02 (Verlegungen zw. Funktionscodes): Altersgruppe bei Zugang + Neugeborenes

die Altersgruppe bei Entlassung wird maximal 1 mal übermittelt und nicht bei jeder Verlegung
Altersgruppe bei Zugang und Neugeborenes können bei jeder Verlegung übermittelt werden

Ändert diese Information etwas an unseren Überlegungen zur Modellierung? @alackerbauer 

Geben wir diese Complexextension also in den MOPEDEncounter und in den Transferencounter? im MopedEncounter ist dann die Altersgruppe bei Entlassung befüllt und im Transferencounter die Altersgruppe bei Zugang + Neugeborenes?

Bleibt mit diesen Überlegungen dann trotzdem die Position am admission Element?

**Comment by alackerbauer** [comment]
vielen dank für die verständliche Erklärung.

Ich würde alles auf den TransferEncounter geben. Wir können das in der $entlassen Operation Business Logik regeln, dass hier beim letzten TransferEncounter die Altersgruppe zum Zeitpunkt der Entlassung berechnet wird (eignes Ticket #258 )

Nachdem das admission Property auch Details über discharge beinhält, passt es dennoch gut würde ich sagen.
