### ISSUE TITLE
Bund Profile für Patient und Encounter

### ISSUE THREAD

**Issue by alackerbauer** [HL7Austria/ELGA-MOPED-R5#167]
Begründung: "Die Datenfelder „Aufnahmezahl“ und „Geburtsdatum“ sind ausschließlich in den Datenübermittlungen zwischen den Fonds-KA und den Landesgesundheitsfonds zu befüllen. Das Datenfeld „Datensatz-ID“ ist ausschließlich in den Datenübermittlungen zwischen den Landesgesundheitsfonds und dem Gesundheitsministerium für zu befüllen."

Quelle: LKF-Systembeschreibung 2024

**Comment by 1anja1** [comment]
erledigt in #232 #231 #230 #229
