### ISSUE TITLE
Markdown Template an Beispiel Aufnahme für Use Case Beschreibung

### ISSUE THREAD

**Issue by simonesan** [HL7Austria/ELGA-MOPED-R5#187]
Wie hier:
https://build.fhir.org/ig/IHE/ITI.Finance/ITI-YY1.html
https://build.fhir.org/ig/IHE/ITI.Finance/volume-1.html#actors-and-transactions

Moped <-aufnehmen-> KH

eigener Use case Reiter

**Comment by simonesan** [comment]
Ich habe gesehen es gibt schon sowas Ähnliches in unserem Projekt im Sollprozess Reiter. Inwiefern soll sich der neue Use Case Reiter davon unterscheiden? @alackerbauer 
Ein paar Screenshots davon:
![Image](https://github.com/user-attachments/assets/3f66644a-130a-4873-8c83-ea1f25c81aba)

![Image](https://github.com/user-attachments/assets/f827c951-bd67-46c9-81df-9b10bb769c43)

**Comment by 1anja1** [comment]
https://github.com/IHE/ITI.Finance/blob/master/input/images-source/ActorsAndTransactions.plantuml
https://github.com/IHE/ITI.Finance/blob/master/input/pagecontent/volume-1.md
