### ISSUE TITLE
Korrekturaufforderung relevante Felder und Beispieldaten

### ISSUE THREAD

**Issue by 1anja1** [HL7Austria/ELGA-MOPED-R5#193]
<img width="457" alt="Screenshot 2024-10-24 at 09 08 43" src="https://github.com/user-attachments/assets/96265046-c3db-4e8f-bdf5-631d6e793c5c">

Im Sollprozess: Vorläufige Leistungsabrechnung & Datenmeldung - Vorläufige Freigabe

Welche Felder werden bei einer Korrekturaufforderung seitens des LGF befüllt?
Beispieldatensatz dazu anfordern

**Comment by alackerbauer** [comment]
beispieldaten wurden angefragt.

**Comment by alackerbauer** [comment]
beispieldaten wurden erhalten.
