### ISSUE TITLE
Procedure Identifier mit oder ohne Uhrzeit

### ISSUE THREAD

**Issue by 1anja1** [HL7Austria/ELGA-MOPED-R5#197]
MOPED Identifier = Aufnahmezahl+ICD10Code+Procedure.occurrence(YYYY-MM-DDTHH:MM)

Soll beim Identifier für das Procedure die Uhrzeit inkludiert werden?

Pro: 

- unterschiedliche Procedures mit dem gleichen Code am selben Tag können sonst nicht unterschieden werden -> sollen Leistungen am gleichen Tag unterschieden werden oder erhöht sich da einfach die Anzahl? -> zuerst #195 abklären

Con:

- Uhrzeit eventuell nicht bei jedem Procedure bekannt? (mit Experten abklären)

**Comment by 1anja1** [comment]
Falls Uhrzeit nicht gewünscht muss das Procedure Profil aktualisiert werden

**Comment by alackerbauer** [comment]
ich würde sagen mit Uhrzeit.
