### ISSUE TITLE
Check Diff von Github Issues im Projekt-Board

### ISSUE THREAD

**Issue by alackerbauer** [HL7Austria/ELGA-MOPED-R5#203]
nicht alle tickets sind im board (81 von 86). bitte die restlichen identifizieren und als todo aufnehmen.

**Comment by simonesan** [comment]
Wenn man in Github bei der Issue Suche ein minus davor stellt, kann man filter umkehren. Wenn man also nach "is:open is:issue -project:hl7austria/1" sucht, findet man alle aktiven Issues, die nicht im Board sind. Habe diese Issues ins Board eingefügt.
