### ISSUE TITLE
Bindings sollen System definieren - nicht URL

### ISSUE THREAD

**Issue by alackerbauer** [HL7Austria/ELGA-MOPED-R5#211]
Beispiel Encounter identifier - der sollte ja ein System was als System im ValueSet verwendet wird verwenden und nicht die „url“ vom ValueSet
- 
- das ValueSet ist : [https://termgit.elga.gv.at/ValueSet/hl7-at-patientidentifier](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftermgit.elga.gv.at%2FValueSet%2Fhl7-at-patientidentifier&data=05%7C02%7CAnna.Lin%40fh-hagenberg.at%7Ce41dd3654bfd43ecfcdc08dcf42f53bd%7Cf88d4b736bb24b9aabc7eb96e5a6407c%7C0%7C0%7C638653731345248818%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=i6Ipa2O9NSclmkbJMjUtjgON1Ibix445C43o3stzk4o%3D&reserved=0)
- das CodeSystem aber : [http://terminology.hl7.org/CodeSystem/v2-0203](https://eur02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fterminology.hl7.org%2FCodeSystem%2Fv2-0203&data=05%7C02%7CAnna.Lin%40fh-hagenberg.at%7Ce41dd3654bfd43ecfcdc08dcf42f53bd%7Cf88d4b736bb24b9aabc7eb96e5a6407c%7C0%7C0%7C638653731345270599%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=7Ka1fcE2OrXL9Tcdhtf1OZWz6yPj9jTuwnU29BOv1XE%3D&reserved=0)
```
    "identifier": [
        {
            "type": {
                "coding": [
                    {
                        // "system": "https://termgit.elga.gv.at/ValueSet/hl7-at-patientidentifier",
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                        "code": "VN"
                    }
                ]
            }
```

In diesem Zuge alle Bindings checken und ggf. überarbeiten.

**Comment by simonesan** [comment]
Ich habe mir gerade den QA Report angesehen. Es schaut so aus als ob man bei den Testbeispielen schon das Valueset verwenden muss:
![Image](https://github.com/user-attachments/assets/26412625-3fc1-4729-948b-fccaa79ae468) 
Ich werd mir den Report noch etwas weiter dursehn und versuchen die Urls zu fixen

**Comment by alackerbauer** [comment]
beispiel vom test encounter 1:

//Ursache
* reason[+].use.coding.system = "http://hl7.org/fhir/encounter-reason-use"
* reason[=].use.coding.code = #RV
* reason[=].value = #00


Das System hab ich mir angeschat wenn ich auf die ValueSet Definition der Spec gehe: https://hl7.org/fhir/valueset-encounter-reason-use.html#:~:text=%C2%A0%C2%A0CC-,http%3A//hl7.org/fhir/encounter%2Dreason%2Duse,-Chief%20Complaint
