### ISSUE TITLE
Postman Visualize Tab für Anzeigen von Response Bodies

### ISSUE THREAD

**Issue by alackerbauer** [HL7Austria/ELGA-MOPED-R5#223]
ChatGPT kann wunderbar in wenigen Sekunden Skripte schreiben, die in Postman eingefügt werden können um den Visualize Tab zu konfigurieren. Ein Beispiel Promt ist:

`ich brauche bitte ein postman visualizer script für ein FHIR Bundle das mit Patienten-Daten gefülllt ist: https://learning.postman.com/docs/sending-requests/response-data/visualizer/`

Das ganze eingefügt in den Tests Tab liefert nach Absetzen des Requests eine ansehnliche Version des JSON Bodies. Im Beispiel das Resultat des erstellten Scripts.

Es lohnt sich vl. hier ein paar Beispiel-Visualisierungen zu konfigurieren, damit für künftige Showcases eine bessere Lesbarkeit gegeben ist.

![Image](https://github.com/user-attachments/assets/7b936863-459b-4dda-ac57-0a90acd66b91)

**Comment by simonesan** [comment]
@alackerbauer ich habe das Beispiel von dir mal bei mir nachgebaut und es funktioniert so weit. Für welche Request soll ich den die Scripts erstellen? In unserer Collection sehe ich nur POST und PUT Regests, da kommen vermutlich nicht so viele daten zurück, dass das dort Sinn machen würde, oder?

**Comment by alackerbauer** [comment]
genau. praktisch wäre es jedenfalls für GET Patient mit ziemlich vielen infos (jedenfalls szv nr, name, adresse, gender, birthdate) sowie GET für Encounter inkl. datensatz id und aufnahmezahl sowie start / ende und status und beliebige weitere Felder.
