### ISSUE TITLE
Excel File aktualisieren mit deutschen Extension-Namen

### ISSUE THREAD

**Issue by simonesan** [HL7Austria/ELGA-MOPED-R5#234]
Die neuen Bezeichnungen aus #186 sollen ins Excel File nachgezogen werden

**Comment by 1anja1** [comment]
[FHIR_Mapping_for_IG_new.xlsx](https://github.com/user-attachments/files/17556541/FHIR_Mapping_for_IG_new.xlsx)

**Comment by simonesan** [comment]
Hier das neue Excel File: @1anja1 
[FHIR_Mapping_for_IG_new.xlsx](https://github.com/user-attachments/files/17568092/FHIR_Mapping_for_IG_new.xlsx)

soll ich es auch auf GIT hochladen?

**Comment by 1anja1** [comment]
Nein, du musst es nicht hochladen. Das erledige ich in #255.
