### ISSUE TITLE
Fristende Extension

### ISSUE THREAD

**Issue by alackerbauer** [HL7Austria/ELGA-MOPED-R5#235]
Kann diese Extension auch anstelle von "Fristende" unter `CoverageEligibilityResponse.insurance.benefitPeriod.end` abgebildet werden?

1 Stelle alphanumerisch

- `0` – kein Fristende
- `1` – Fristende

Befristungen sind in folgenden Fällen vorgesehen:

-  Bei zeitlichen Beschränkungen aufgrund einer zu erwartenden, nachfolgenden medizinischen Hauskrankenpflege
- Bei Vorhersehbarkeit des Eintritts einer Asylierung
- Bei unsicherer, versicherungsrechtlicher Entwicklung
Bei den ersten beiden Punkten wird von den Krankenversicherungsträgern das Fristende individuell
gesetzt. Beim dritten Punkt wird im Regelfall eine generelle Tagesbeschränkung erfolgen, weil die
Versichertenanspruchserklärung in die Zukunft gerichtet ist und der Krankenversicherungsträger
seine Zuständigkeit von vornherein nur für einen bestimmten Zeitraum annehmen kann (Ausleistungssituation gem. § 122 ASVG).

Durch die Angabe eines Fristendes wird signalisiert, dass bei einem über das Fristende hinaus dauernden Aufenthalt eine Verlängerungsanzeige vorzulegen ist.

All das kann theoretisch durch ein Befüllen der benefitPeriod.end abgebildet werden, und das Krankenhaus muss wissen, dass wenn dieses Feld befüllt ist, ggf. eine Verlängerungsanzeige vorzulegen ist.

**Comment by alackerbauer** [comment]
@1anja1 spricht da was dagegen? Wenn nicht, werd ich das mal so an den Dachverband bzw. auch SVC kommunizieren.

**Comment by 1anja1** [comment]
@alackerbauer Ich finde das ist ein guter Ansatz den wir so verfolgen sollten sofern die Stakeholder zustimmen.
