### ISSUE TITLE
Analyse Extension Reduktion

### ISSUE THREAD

**Issue by alackerbauer** [HL7Austria/ELGA-MOPED-R5#236]
- **Fristende** unter `CoverageEligibilityResponse.insurance.benefitPeriod.end` (ticket #235)?
- **VDASID** unter Coverage.identifier (ticket #153)
- **Rezeptgebührenbefreit** unter `CoverageEligibilityResponse.insurance.item.benefit.type` mit eigenem Benefit-ValueSet mit Wert Rezeptgebührenbefreit
- **Kostenanteilsbefreit** unter `CoverageEligibilityResponse.insurance.item.benefit.type` mit eigenem Benefit-ValueSet mit Wert Kostenanteilsbefreit
- **Verpflegungskosten-Beitragsbefreiung** unter `CoverageEligibilityResponse.insurance.item.benefit.type` mit eigenem Benefit-ValueSet mit Wert Verpflegungskosten-Beitragsbefreiung
- **Sonderklasse (KLAS)** unter `CoverageEligibilityResponse.insurance.item.benefit.type` mit eigenem Benefit-ValueSet mit Wert Sonderklasse

**Comment by alackerbauer** [comment]
@1anja1 hast du da eine Meinung dazu?

Ich weiß, einige davon kommen von der VDAS und die modellieren es so, aber eigentlich betreffen diese Dinge nicht die Coverage selbst, sondern einen bestimmten Zeitpunkt mit bestimmten Benefit, also würde es in der CoverageEligibilityResponse grundsätzlich gut passen.

**Comment by 1anja1** [comment]
VDASID und Fristende sehe ich auch so. 

bezüglich Rezeptgebührenbefreit, Kostenanteilsbefreit, Verpflegungskosten-Beitragsbefreiung und Sonderklasse:  Nur die Verpflegskosten Beitragsbefreiung und die Sonderklasse sind Felder die wir modellieren müssen (Teil von KaOrg) - die anderen sind nur dabei, weil diese Teil des VDAS Coverage Profils waren und wir dieses 1:1 übernommen haben - es macht also keinen Sinn die anderen in unsere CoverageEligibilityResponse zu übernehmen. Wir müssen hier aber aufpassen, dass wir nicht inkompatibel werden mit VDAS on FHIR. Das muss gut abgestimmt werden, damit einer zukünftigen Anbindung nichts im Weg steht.
