### ISSUE TITLE
Error case mismatch beheben

### ISSUE THREAD

**Issue by 1anja1** [HL7Austria/ELGA-MOPED-R5#238]

**Comment by simonesan** [comment]
Eigentlich muss man nur den Temp Folder lokal löschen, dann sollte alles wieder durchlaufen. Das muss jeder einmal selbst lokal machen, damits wider durchläuft. Im temp folder weden die alten IDs gecashed und wenn man die umbenennen will muss man den löschen. Hätte ich Gesten erwähnen sollen :/

**Comment by simonesan** [comment]
Gibts da jetzt noch Fragen oder kann ich das Issue schließen? @1anja1 @alackerbauer
