### ISSUE TITLE
Mapping-Änderungen Ka-Org

### ISSUE THREAD

**Issue by alackerbauer** [HL7Austria/ELGA-MOPED-R5#26]
# Identifikationsteil
* FANU: Diskussion: Fallnummer raus? (wiederaufnahmen nach Urlaub)
* KOST: Account.coverage extension
* VSTR: Account.coverage.payor aber nur, wenn Account.status mindestens auf "SV Verarbeitet" ist
* BKANR: GDA-OID über Account.owner

# Aufnahmeanzeige
* KLAS wird zwar im CoverageEligibilityRequest übernommen, sollte aber ggf. in der Account wandern (?)

# Versichertenansprucherklärung
* Versichertenanspruchserklärung

# Entlassungsanzeige
* klären, ob hier alle Diagnosen (Haupt- und Zusatzdiagnosen) angeführt werden

# Generell
* Die Referenz im Claim zum Account sollte umgekehrt dargestellt werden von im Account (zum Claim) realisiert werden. --> eigenes Ticket
* Grundsätzlich ist die Idee, dass CoverageEligibilityRequest und Claim lediglich Dinge von anderen Ressourcen referenzieren und nur zusätzliche Elemente abspeichern, die als Parameter der Operation mitgegeben werden, die dann auch nur für diesen Request relevant sind. Es sollte nicht als Container dienen um Dinge später abzuholen. Falls da etwas dabei ist das man später noch braucht, ist es in Account besser aufgehoben.

**Comment by 1anja1** [comment]
- [x] Fallnummer -> AnzahlBeurlaubungen

**Comment by 1anja1** [comment]
- [x] KLAS laut Operation jetzt im CoverageEligibilityRequest festgelegt
- [x] KOST und VSTR werden separat diskutiert in #131 
- [x] BKANR: GDA-OID über Account.owner passt
- [x] AccountRef existiert
