### ISSUE TITLE
Frage Element: AnzahlVerlegungen

### ISSUE THREAD

**Issue by alackerbauer** [HL7Austria/ELGA-MOPED-R5#43]
Ist dieses Element was vorher die Fallnummer war? [AnzahlVerlegungen](https://fhir.hl7.at/r5-ELGA-MOPED-main/StructureDefinition-MOPEDEncounter-definitions.html#Encounter.extension:AnzahlVerlegungen)

Das ist relevant für die Operation https://fhir.hl7.at/r5-ELGA-MOPED-main/OperationDefinition-MOPED.Patient.Verlegen.html --> siehe Schritt 3.

**Comment by 1anja1** [comment]
Nein - die Fallnummer wird nun zu AnzahlBeurlaubungen und die Positionsnummer zu AnzahlVerlegungen. Sofern doch beschlossen wird, dass die Anzahl der Beurlaubungen nicht mehr notwendig ist kann diese wieder entfernt werden. 
Details siehe Tabelle:

|Resource | FHIRPath | Extension | KaOrg Abkürzung | KaOrg Feld  |  Beschreibung  | LKF Abkürzung| LKF Feld|
|-- | -- | -- | -- | -- | -- | -- | -- |
MOPEDAccount | .extension | .AnzahlBeurlaubungen | FANU | Fallnummer | Anzahl der Wiederaufnahmen nach Urlaub |   |   |  
MOPEDAccount | .extension | AnzahlVerlegungen |   |   | fortlaufende Nummer; wird bei jeder Verlegung & Urlaub erhöht | ABTPOS | Hauptkostenstelle/Fachgebiet – Positionsnummer|
