### ISSUE TITLE
Altersgruppe und Neugeborenes zu TransferEncounter (statt MOPEDEncounter)

### ISSUE THREAD

**Issue by alackerbauer** [HL7Austria/ELGA-MOPED-R5#55]
damit es immer mitgeschickt wird.

**Comment by 1anja1** [comment]
Soll die Altersgruppe als Integer oder als Code mit den einzelnen Gruppen repräsentiert werden?
<img width="990" alt="Screenshot 2024-09-25 at 13 06 08" src="https://github.com/user-attachments/assets/6535f24a-93b2-470d-a250-c74c8e586cdd">

**Comment by alackerbauer** [comment]
Ich finde, das ist nicht eindeutig. Ich denke, ein unsignedInt wär hier ok. Das werden wir aber in der AG Moped noch absprechen und ggf. auf Code abändern.

**Comment by 1anja1** [comment]
Laut AG MOPED soll die Altersgruppe codiert werden
