### ISSUE TITLE
Harmonisierung ValueSet Entlassungsschlüssel / 

### ISSUE THREAD

**Issue by alackerbauer** [HL7Austria/ELGA-MOPED-R5#70]
# Ka-Org:

1 – Urlaub
2 – Rehabilitation angezeigt
3 – Asylierung
4 – Entlassung gegen Revers
5 – AUVA Ende der Arbeitsunfähigkeit
6 – AUVA Ende der ambulanten Behandlung
7 – AUVA Ende der ambulanten Behandlung und Ende der Arbeitsunfähigkeit
8 – Ende Rehabilitationsaufenthalt stationär
9 – Ende Rehabilitationsaufenthalt ambulant
E – Entlassung aus dem Krankenhaus
K – Ende Kurheilverfahren stationär
T – Transfer in eine andere Krankenanstalt
S – Sterbefall
A –Krankenhausinterne Verlegung vom Bereich der Rehabilitation und vom ausschließlichen
Bereich der Pflege in den allgemeinen stationären Bereich (inkl. Intensivbereich)
H –Abschluss eines Aufenthaltes im halbstationären Bereich oder krankenhausinterne Verlegung in den halbstationären Bereich
R – Krankenhausinterne Verlegung in den Bereich der Rehabilitation
P – Krankenhausinterne Verlegung in den ausschließlichen Bereich der Pflege

# LKF (stationär)

E - Entlassung aus dem Krankenhaus
T - Transfer in ein anderes Krankenhaus
S - Sterbefall
A - Krankenhausinterne Verlegung vom Bereich der Rehabilitation und vom
ausschließlichen Bereich der Pflege in den allgemeinen stationären Bereich (inkl.
Intensivbereich)
R - Krankenhausinterne Verlegung in den Bereich der Rehabilitation
P - Krankenhausinterne Verlegung in den ausschließlichen Bereich der Pflege
L - Kennzeichen der Datensätze, die zum Zeitpunkt der Asylierung dokumentarisch
abgeschlossen werden
V - Kennzeichen für noch nicht abgeschlossene Aufenthalte von am Jahresende
verbleibenden Patient:innen
4 - Entlassung gegen Revers

# LKF (spitalsambulant/extramural)
1 - Zuweisung an eine:n Allgemeinmediziner:in
2 - Zuweisung an einen Facharzt/eine Fachärztin
3 - Zuweisung an die eigene/eine andere Krankenanstalt zur ambulanten
Weiterbetreuung
5 - Zuweisung an die eigene/eine andere Krankenanstalt zur stationären Aufnahme
6 - Wiederbestellung
7 - Behandlungsende, keine Zuweisung
8 - Sterbefall
9 - Sonstige Abgangsart

**Comment by alackerbauer** [comment]
Vorschlag: Alle Werte von Ka-ORG plus zusätzlich `L`und `V` von LKF:

[Uploading excel-mapping-entlassung-abgangsart.xlsx…]()

**Comment by alackerbauer** [comment]
Das ValueSet Abgangsart ist momentan leer: https://fhir.hl7.at/r5-ELGA-MOPED-main/ValueSet-moped-abgangsart-valueset.html

Das ValueSet Entlassungsart ist gefüllt mit der Vereinigung von Ka-ORG und LKF, beinhält jedoch weitere Werte (siehe unten). Unter anderem wird hier LKF 4 als Sterbefall geführt, der lt. LKF Dokumentation allerdings mit einem 'S' codiert wird.

LKF_1 | Zuweisung an eine:n Allgemeinmediziner:in
-- | --
LKF_2 | Zuweisung an einen Facharzt/eine Fachärztin
LKF_3 | Zuweisung an die eigene/eine andere Krankenanstalt zur ambulanten Weiterbetreuung
LKF_5 | Zuweisung an die eigene/eine andere Krankenanstalt zur stationären Aufnahme
LKF_6 | Wiederbestellung
LKF_7 | Behandlungsende, keine Zuweisung
LKF_8 | Sterbefall
LKF_9 | Sonstige Abgangsart

**Comment by alackerbauer** [comment]
@1anja1 können wir das ValueSet "Abgangsart" löschen? Oder gibt es einen Grund warum es separat angeführt ist?

**Comment by 1anja1** [comment]
Das ValueSet Abgangsart wäre für das Feld "ABTAART | Hauptkostenstelle – Abgangsart":
<img width="957" alt="Screenshot 2024-09-30 at 09 40 53" src="https://github.com/user-attachments/assets/1fe2d7b9-2839-491d-b1fc-882b8e6ee192">

Diese Codes sind nicht 1:1 so in der Entlassungsart enthalten - oder wie würdest du diese zuordnen? @alackerbauer
