### ISSUE TITLE
Abgangsart (MOPEDTransferEncounter) vs. Entlassungsart (MOPEDEncounter)

### ISSUE THREAD

**Issue by alackerbauer** [HL7Austria/ELGA-MOPED-R5#71]
Gibt es einen Grund, dass diese unterschieden werden (i.e. unterschiedliche ValueSets)? Derzeit ist ja im Entlassungsart-Value-Set die Vereinigung aller möglicher Ausprägungen enthalten.

Ist das die Hauptkostenstelle Abgangsart?

1 - Lebend
2 - Lebend mit Therapiereduktion
3 - Gestorben
4 - Gestorben mit Therapiereduktion

Kann man von der Entlassungsart auf diese schließen?

Die Frage stellt sich, ob man bei der Entlassung ($entlassen) damit automatisch den letzten offenen Transfer-Encounter schließen könnte.

**Comment by 1anja1** [comment]
### Entlassungsart (MOPEDEncounter):
ENTS Entlassungsschlüssel (KaOrg) = ENTLART Entlassungsart (KaOrg) = Entlassungs-/Abgangsart (LKF):
<img width="544" alt="Screenshot 2024-09-27 at 10 39 42" src="https://github.com/user-attachments/assets/48f78d20-c200-464c-b0ce-e2957b9afcb1">

### Abgangsart (MOPEDTransferEncounter):
1 - Lebend
2 - Lebend mit Therapiereduktion
3 - Gestorben
4 - Gestorben mit Therapiereduktion

Laut MOPED Mapping können die Werte der Abgangsart nicht abgeleitet werden. Die Abgangsart wird außerdem nur bei Intensivpatienten befüllt - Logik wäre daher um einiges komplizierter.

**Comment by alackerbauer** [comment]
Ah, also wird die Abgangsart von einer Abteilung nur befüllt, wenn der Patient für den einen TransferEncounter der Funktionscode Intensivabteilung hat? Ansonsten wird das nicht je Abteilung befüllt sondern nur im MOPEDEncounter bei Entlassung?

**Comment by 1anja1** [comment]
So wie ich das verstanden habe ja - evtl. wäre es aber gut das nochmal abzuklären.
