### ISSUE TITLE
Patientenaufnahme direkt auf Abteilung?

### ISSUE THREAD

**Issue by alackerbauer** [HL7Austria/ELGA-MOPED-R5#73]
Für die $aufnehmen Operation ist relevant, ob davon ausgegangen werden kann, dass bei freigegebener Aufnahme ein Patient immer direkt auf eine Abteilung (i.e. einen Funktionscode) aufgenommen wird oder hier zu einem späteren Zeitpunkt die erste "Verlegung" stattfindet.

**Comment by alackerbauer** [comment]
Indikator Testfall 1: hier passiert die Aufnahme und die "Verlegung" auf die Abteilung zur selben Zeit, nämlich um 19:33.

**Comment by 1anja1** [comment]
In der K01 (Aufnahmeanzeige) wird bereits ein Funktionscode übermittelt. Somit gehe ich davon aus, dass der Patient direkt auf eine Abteilung aufgenommen wird.
