### ISSUE TITLE
Änderungen bei Operation $entlassen und $verlegen

### ISSUE THREAD

**Issue by alackerbauer** [HL7Austria/ELGA-MOPED-R5#78]
Lt. Diskussion hier: https://github.com/HL7Austria/ELGA-MOPED-R5/issues/71 wird die Abgangsart nur beim Abgang von der Intensivstation befüllt. Dies kann durch Verlegung oder Entlassung passieren. In der Entlassung sollte somit die Option für Abgangsart optional als Parameter gegeben sein. In der Verlegung sollte eine Beschreibung stehen, dass der optionale Parameter Abgangsart nur befüllt wird, wenn es sich um den Funktionscode Intensivstation handelt. --> Funktionscode ....81 ist Intensivstation

**Comment by 1anja1** [comment]
in $entlassen fehlt die Abgangsart noch
