### ISSUE TITLE
Frage: Wann/Wie (also in welcher Operation) werden die Prioritäten für die möglichen Coverages vergeben?

### ISSUE THREAD

**Issue by 1anja1** [HL7Austria/ELGA-MOPED-R5#80]
Szenario: von der VDAS Abfrage kommen mehrere Coverages zurück -> der Patient wählt die Coverage aus an die dann der CoverageEligibilityRequest gestellt werden soll -> diese Entscheidung wird durch das Feld Account.coverage.priority repräsentiert

Diese Information muss aber, um sie in der $anfragen Operation verwenden zu können bereits vorhanden sein. Wann/Wie wird dieses Feld befüllt?

Gedanke für Use Cases außerhalb des Sunshine Case -> würde dann bei einer negativen Response automatisch/manuell ein Request mit der Coverage mit der nächstniedrigeren Priority durchgeführt werden?

**Comment by alackerbauer** [comment]
Das passiert beim CoverageEligibilityRequest Erstellen ($anfragen). Hier wird ein insurer mitgegeben, mit dem sich Moped die relevante Coverage aus dem Account heraussucht. Eine Prioritäten-Liste ist mir im echten Anwendungsfall nicht bekannt, vielmehr muss der Patient eine der Versicherungen auswählen die zum Zug kommt.

**Comment by 1anja1** [comment]
Kann es dabei aber vorkommen, dass es mehrere Coverages mit dem gleichen insurer gibt? Weil dann wäre der Inputparameter alleine nicht ausreichend.

**Comment by alackerbauer** [comment]
update: es passiert sogar früher, direkt bei der Aufnahme. Der Patient wird dabei gefragt und muss sich auf eine der Versicherungen festlegen.
