### ISSUE TITLE
SIcherstellen, dass Operation-Felder auch so in Profilen vorkommen

### ISSUE THREAD

**Issue by alackerbauer** [HL7Austria/ELGA-MOPED-R5#84]
vor allem die Felder für $aufnehmen und $verlegen in einem ersten schritt

**Comment by 1anja1** [comment]
$aufnehmen sollte passen - bei $ verlegen bin ich nicht mehr ganz fertig geworden und siehe Ticket #95

**Comment by alackerbauer** [comment]
ticket #95 ist erledigt - der Rest sollte noch fertig überprüft werden.
