### ISSUE TITLE
Testfall 2 update nachziehen

### ISSUE THREAD

**Issue by 1anja1** [HL7Austria/ELGA-MOPED-R5#86]
- AnzahlBeurlaubungen
- Aufnahme code

**Comment by 1anja1** [comment]
- AnzahlBeurlaubungen
- AnzahlVerlegungen
bei Testfall 1 & 2

**Comment by alackerbauer** [comment]
email antwort mit diff wird erwartet

**Comment by 1anja1** [comment]
in examples/Test2 folgende dinge ausbessern:
Anzahl Beurlaubungen überprüfen
Anzahl Verlegungen überprüfen
K05:       FANU =  1
                ENTL  = 20240812
 
X01:
                Entlassdatum  =  20240812
Im 2. X02-Datensatz: (im TransferEncounter 3)
                Hauptkostenstelle – Abgangsuhrzeit = 1141

**Comment by 1anja1** [comment]
Es gibt eine Abteilung doppelt (2 MOPEDOrganizationAbteilung Ressourcen mit gleichem Funktionscode) - die 2. löschen und dann im Test2 Ordner die Referenzen überprüfen und die Referenzen der gelöschten Abteilung updaten

**Comment by simonesan** [comment]
Hab die Doppelte abteilung die im letzten Komentar erwähnt wird gelöscht und die refs geändert.
Habe jedoch keine Ahnung was ich mit den vorletzen Komentar machen soll:

> in examples/Test2 folgende dinge ausbessern:
> Anzahl Beurlaubungen überprüfen
> Anzahl Verlegungen überprüfen
> K05: FANU = 1
> ENTL = 20240812
> 
> X01:
> Entlassdatum = 20240812
> Im 2. X02-Datensatz: (im TransferEncounter 3)
> Hauptkostenstelle – Abgangsuhrzeit = 1141

ist da noch was zu machen? @1anja1 @alackerbauer 
Ich nehme an die davor erwähnten dinge sind schon passiert da das Issue reopened wurde?

**Comment by 1anja1** [comment]
@simonesan es soll in examples/Test2 überprüft werden, ob alle diese changes bereits in den Beispielen vorhanden sind. Die Anzahl der Beurlaubung und der Verlegungen beispielsweise ist in den Testdaten noch gar nicht vorhanden. 
```
* extension[+].url = "http://example.org/StructureDefinition/moped-ext-AnzahlVerlegungen"
* extension[=].valueUnsignedInt = ?
* extension[+].url = "http://example.org/StructureDefinition/moped-ext-AnzahlBeurlaubungen"
* extension[=].valueUnsignedInt = ?
```

**Comment by 1anja1** [comment]
1 Urlaub und 5 Verlegungen

**Comment by simonesan** [comment]
@1anja1 ich hab jetzt mal das mit Verlegungen und Beurlaubungen gemacht, auch wenn ich keine Ahnung habe wie du auf die Werte gekommen bist? Fehlen mir da irgendwelche Infos?

Der Rest ist für mich leider immer noch sehr kryptisch. Im Issue werden changes erwähnt, die ich nachziehen soll, aber um welche changes handelt es sich?

Was ist mit K05 gemeint? die K05 Meldung? was heißt das im Bezug zu den Testfällen? Soll ich da wo die Fallnummer und das Entlassungsdatum setzen? aber wo?

was ist X01?

X02 ist erwähnt das, dass der TransferEnconter 2 ist, ich nehme an da soll ich die actualPeriod.end aufs gleiche Datum wie actualPeriod.start setzten und die Zeit auf 11:41 setzen? aber die Uhrzeit bei start ist auch schon 11:41?

Ich weiß, das sind ein haufen Fragen, aber ich bin einfach etwas verwirrt mit den Infos die ich habe, ich hab das Gefühl ich hab nicht alle, die ich für das Issue brauche.

**Comment by 1anja1** [comment]
@simonesan ja das ist etwas verwirrend
K05: 
FANU = 1 _dies bedeutet, dass die Fallnummer 1 ist -> das entspricht bei uns der Anzahl der Beurlaubungen (siehe mapping Excel) und hast du somit schon ausgebessert_
ENTL = 20240812 _bedeutet, dass das Entlassungsdatum diesem Datum entsprechen soll dies ist auch gleichzeitig das Entlassungsdatum aus X01 weiter unten_

X01:
Entlassdatum = 20240812 _siehe Kommentar bei ENTL_
Im 2. X02-Datensatz: (im TransferEncounter 2)
Hauptkostenstelle – Abgangsuhrzeit = 1141 _im Transferencounter 2 soll die Abgangsuhrzeit auf 1141 ausgebessert werden_
