### ISSUE TITLE
Update Mapping Excel Files

### ISSUE THREAD

**Issue by 1anja1** [HL7Austria/ELGA-MOPED-R5#98]
Im IG wurden an den Profilen einige Änderungen vorgenommen. Diese müssen in die Mappingtabellen nachgezogen werden.
Die Mappingpfade aller Elemente sollen überprüft und aktualisiert werden einerseits hier:
[FHIR_Mapping_for_IG_new.xlsx](https://github.com/user-attachments/files/17201486/FHIR_Mapping_for_IG_new.xlsx)
und andererseits im Mapping File welches bereits nach Ressourcen aufgeteilt ist:
[FHIR Mapping by Resource.xlsx](https://github.com/user-attachments/files/17201506/FHIR.Mapping.by.Resource.xlsx)

Dazu im folder input/fsh: 
![Screenshot 2024-10-01 at 10 01 21](https://github.com/user-attachments/assets/38f51086-4412-4ad0-9933-c90b5521584d)
alle Files exklusive der "xxx-operation-xxx" durchgehen und mit den excel files abgleichen. Manche Dinge (va. Extensions) haben sich zwischen den Ressourcen verschoben bzw. sind neu hinzu gekommen. 

z.b. die Extension vdasid war bisher: CoverageEligibilityRequest | .extension | VDASID
befindet sich jetzt aber in Account: Account | .extension | VDASID

Die fertigen excel Files bitte wieder unter diesem Ticket kommentieren.

**Comment by 1anja1** [comment]
Das Feld:  ```EAKRO | Akronym des zuständigen Trägers```  soll den Pfad: ```HL7ATCoreOrganization | .identifier:alias``` bekommen

**Comment by simonesan** [comment]
[FHIR_Mapping_for_IG_new.xlsx](https://github.com/user-attachments/files/17244217/FHIR_Mapping_for_IG_new.xlsx)
Hier mal die Änderungen für das erste File. Alle Änderungen hab ich mit lila Schrift markiert. 
@1anja1 pls check

**Comment by 1anja1** [comment]
ANWESEND| Physische Anwesenheit | TransferEncounter | .subjectStatus

**Comment by 1anja1** [comment]
- [ ] #121 zweite paths ins mapping einfügen
